name = "gooserave smp"
author = "arkadst"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19a95f2ed9fbd09b84effa22957c261793fe7341c572c59d92f4e594f84e72a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
