name = "gooserave smp"
author = "arkadst"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c1f88bd62779c8d9d085ad3747f1e6a38929826915663818e1aad96f16903e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
