name = "gooserave smp"
author = "arkadst"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e84ee2e6dbe0a258b791e5f1345b8e537d182b667246883c21270bf44fa5c6db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
